
version: "3.7"


services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: db # The PostgreSQL default database (automatically created at first launch)
  frontend:
    build: ./frontend
    ports:
      - 4200:80
    restart: unless-stopped

  backend:
    build: ./backend
    
    depends_on:
      - database
    ports:
      - 8080:8080
    restart: unless-stopped
  